[paths]
PROGRAM_MOUNT=/mnt/sovereign/program
DATA_MOUNT=/mnt/sovereign/data
ENV_DIR=/mnt/sovereign/data/env
LOG_DIR=/mnt/sovereign/data/logs
DB_DIR=/mnt/sovereign/data/postgres/data
REDIS_DIR=/mnt/sovereign/data/redis/data
CADDY_DATA_DIR=/mnt/sovereign/data/caddy/data
CADDY_CONFIG_DIR=/mnt/sovereign/data/caddy/config
TOR_DIR=/mnt/sovereign/data/tor
BACKUP_DIR=/mnt/sovereign/data/backups
SSL_DIR=/mnt/sovereign/data/postgres/ssl
