#!/bin/bash
if [[ $EUID -ne 0 ]]; then echo "Run with: sudo bash $0"; exit 1; fi

REAL_USER="${SUDO_USER:-$(logname 2>/dev/null || whoami)}"
REAL_HOME=$(getent passwd "$REAL_USER" | cut -d: -f6)
TC="$REAL_HOME/threadcount"

echo "=== FRESH START ==="

# Stop and wipe everything
cd "$TC" 2>/dev/null
docker compose down -v --remove-orphans 2>/dev/null || true
docker stop $(docker ps -aq) 2>/dev/null || true
docker rm -f $(docker ps -aq) 2>/dev/null || true
docker volume rm $(docker volume ls -q) 2>/dev/null || true
echo "✓ Cleaned"

# Update code
su - "$REAL_USER" -c "cd $TC && git pull"
echo "✓ Code updated"

# Write correct .env
PG_PASS=$(openssl rand -hex 32)
FERNET=$(openssl rand -base64 32)
BOT_KEY=$(openssl rand -hex 24)
HMAC=$(openssl rand -hex 24)
OP_PASS=$(openssl rand -hex 16)

cat > "$TC/.env" << 'HEADER'
# Generated by fresh-start.sh
HEADER

cat >> "$TC/.env" << EOF
POSTGRES_USER=sovereign
POSTGRES_PASSWORD=$PG_PASS
POSTGRES_DB=sovereign_commerce
POSTGRES_HOST=postgres
POSTGRES_PORT=5432
REDIS_URL=unix:///var/run/redis/redis.sock
TELEGRAM_BOT_TOKEN=AAGL_FKdviqw3egkvJbdoPuNCr_Eo_gwx74
TELEGRAM_ADMIN_IDS=5410979519
API_HOST=0.0.0.0
API_PORT=8000
API_BASE_URL=http://api:8000
JWT_ALGORITHM=RS256
JWT_ACCESS_TOKEN_EXPIRE_MINUTES=60
JWT_REFRESH_TOKEN_EXPIRE_HOURS=24
FERNET_KEY=$FERNET
BOT_API_KEY=$BOT_KEY
BOT_HMAC_SECRET=$HMAC
OPERATOR_USERNAME=admin
OPERATOR_PASSWORD=$OP_PASS
BOT_RATE_LIMIT_PER_MINUTE=30
BOT_SESSION_TIMEOUT_MINUTES=15
LOGIN_MAX_ATTEMPTS=5
LOGIN_LOCKOUT_MINUTES=30
BACKUP_DIR=/backups
BACKUP_RETENTION_DAYS=30
LOG_LEVEL=INFO
ENVIRONMENT=production
DEBUG=false
SOVEREIGN_MODE=true
EOF

echo "✓ .env written"
echo "  Operator: admin / $OP_PASS"

# Start docker
systemctl is-active --quiet docker || { systemctl start docker; sleep 3; }

# Build and launch
cd "$TC"
docker compose up --build -d 2>&1 | tail -10
echo ""
echo "Waiting 90 seconds..."
sleep 90

echo ""
echo "=== STATUS ==="
docker ps --format "table {{.Names}}\t{{.Status}}"
echo ""
echo "=== API LOG ==="
docker logs sovereign-api 2>&1 | tail -15
echo ""
echo "=== TEST ==="
echo "Dashboard: $(curl -s -o /dev/null -w '%{http_code}' http://localhost)"
echo "API: $(curl -s http://localhost/api/v1/health 2>/dev/null)"
echo ""
